---
 - name: Install uninstall package
   hosts: target1
   gather_facts: false
   become: true
   tasks: 
   - name: install-uninstall package
     yum:
      name: "{{pkg}}"
      state: "{{state}}"
     