---
- name: installing mysql server
  hosts: target
  gather_facts: false
  become: true
  tasks:
  # - name: updating all packages
  #   yum: 
  #    name: "*"
  #    state: latest
  - name: installing mysql-server
    yum: 
     name: mysql-server
     state: present
  - name: start the mysql mysql-server
    service:
     name: mysqld
     state: restarted