---
 - name: memnership operators
   hosts: pranab_ansible_ec2
   gather_facts: false
   become: true
   tasks:
    - name: "get info about pakages" 
      command: " {{ item }} --version"
      loop:
      - git
      - httpd
      register: out

    - name: "display the output"
      debug: msg="{{ out }}"